### ISSUE TITLE
API for Posts not working

### ISSUE THREAD

**Issue by Lucas-Erkana** [Progress2002/Blog-App#16]
After adding a user 1 and post 1:
![image](https://github.com/Progress2002/Blog-App/assets/41428579/e4ec8786-c11e-4874-b524-562863e27fdd)

then after entering: http://127.0.0.1:3000/api/users/1/posts
![image](https://github.com/Progress2002/Blog-App/assets/41428579/98d0a3ad-8aff-4ddf-b66d-8c30eaf3a291)

Kindly change the following variable to user_id to fix the issue:
https://github.com/Progress2002/Blog-App/blob/fd06fbb5343f8adf4a25f42cfaf7f561d2f93bf9/app/controllers/api/posts_controller.rb#L5

After applying this:
![image](https://github.com/Progress2002/Blog-App/assets/41428579/62517a1e-7db1-4d33-af8f-fa78e7422b79)

This is what happened:
![image](https://github.com/Progress2002/Blog-App/assets/41428579/4bc8345f-ffb7-4395-a503-9a1d311fcf27)

**Comment by Progress2002** [comment]
Hello @Lucash2022, thanks for your observation, the project has been updated.
