### ISSUE TITLE
Make sure that everything is documented in a professional way

### ISSUE THREAD

**Issue by Lucas-Erkana** [Progress2002/Blog-App#6]
https://github.com/Progress2002/Blog-App/blob/0e238f960700ad13949c92f6e450ef038f019ecc/README.md?plain=1#L58

Kindly edit this to 
![image](https://github.com/Progress2002/Blog-App/assets/41428579/c020ea9e-acd9-4381-a507-4b37e7cebf54)
 in order to Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

**Comment by Progress2002** [comment]
Hello @Lucash2022, thanks for the observation, the file has been updated.
